"""Stable market-data domain codes."""

from enum import StrEnum


class Market(StrEnum):
    CN_SSE = "CN.SSE"
    CN_SZSE = "CN.SZSE"
    INDEX_REFERENCE = "REFERENCE.INDEX"


class InstrumentType(StrEnum):
    EQUITY = "EQUITY"
    ETF = "ETF"
    INDEX = "INDEX"
    CASH = "CASH"


class DataCapability(StrEnum):
    INSTRUMENT_PROFILE = "INSTRUMENT_PROFILE"
    DAILY_BAR = "DAILY_BAR"
    MARKET_SNAPSHOT = "MARKET_SNAPSHOT"
    TRADING_CALENDAR = "TRADING_CALENDAR"
    INSTRUMENT_MASTER = "INSTRUMENT_MASTER"
    INSTRUMENT_TRADING_STATUS = "INSTRUMENT_TRADING_STATUS"
    ADJUSTMENT_FACTOR = "ADJUSTMENT_FACTOR"
    CORPORATE_ACTION = "CORPORATE_ACTION"
    ETF_INSTRUMENT_MASTER = "ETF_INSTRUMENT_MASTER"
    ETF_BENCHMARK = "ETF_BENCHMARK"
    ETF_DAILY_BAR = "ETF_DAILY_BAR"
    ETF_ADJUSTMENT_FACTOR = "ETF_ADJUSTMENT_FACTOR"
    ETF_VALUATION = "ETF_VALUATION"
    INDEX_REFERENCE = "INDEX_REFERENCE"
    INDEX_DAILY_BAR = "INDEX_DAILY_BAR"
