"""Provider runtime contracts and immutable models."""

from aic_backend.provider_runtime.factory import ProviderFactory
from aic_backend.provider_runtime.health import ProviderHealthManager
from aic_backend.provider_runtime.interfaces import (
    Clock,
    IdGenerator,
    MetricsCollector,
    Provider,
    ProviderBuilder,
    ProviderInvocationHandler,
    ProviderRuntimePort,
)
from aic_backend.provider_runtime.invocation import ProviderInvocationManager
from aic_backend.provider_runtime.lifecycle import ProviderLifecycleManager
from aic_backend.provider_runtime.models import (
    CapabilityMode,
    HealthCheckPolicy,
    HealthCheckResult,
    HealthStatus,
    InvocationErrorDetail,
    InvocationRecord,
    ProviderAttribution,
    ProviderCandidate,
    ProviderCapability,
    ProviderCapacitySnapshot,
    ProviderCooldownSnapshot,
    ProviderDefinition,
    ProviderEventType,
    ProviderExclusionReason,
    ProviderInvocationRequest,
    ProviderInvocationResponse,
    ProviderInvocationResult,
    ProviderMetadata,
    ProviderMetricsSnapshot,
    ProviderRegistration,
    ProviderRegistrySnapshot,
    ProviderRequestContext,
    ProviderRuntimeEvent,
    ProviderSelectionReason,
    ProviderSnapshot,
    ProviderStatus,
    ProviderType,
    QualityScoreBreakdown,
    SelectionDecision,
)
from aic_backend.provider_runtime.registry import ProviderRegistry
from aic_backend.provider_runtime.scoring import QualityScorer
from aic_backend.provider_runtime.selector import ProviderSelector
from aic_backend.provider_runtime.system import UtcClock, UuidIdGenerator

__all__ = [
    "CapabilityMode",
    "Clock",
    "HealthCheckResult",
    "HealthCheckPolicy",
    "HealthStatus",
    "IdGenerator",
    "InvocationRecord",
    "InvocationErrorDetail",
    "MetricsCollector",
    "Provider",
    "ProviderBuilder",
    "ProviderAttribution",
    "ProviderCandidate",
    "ProviderCapability",
    "ProviderCapacitySnapshot",
    "ProviderCooldownSnapshot",
    "ProviderDefinition",
    "ProviderEventType",
    "ProviderInvocationHandler",
    "ProviderInvocationManager",
    "ProviderInvocationRequest",
    "ProviderInvocationResponse",
    "ProviderInvocationResult",
    "ProviderMetadata",
    "ProviderMetricsSnapshot",
    "ProviderFactory",
    "ProviderHealthManager",
    "ProviderLifecycleManager",
    "ProviderRegistration",
    "ProviderRegistry",
    "ProviderRegistrySnapshot",
    "ProviderRequestContext",
    "ProviderExclusionReason",
    "ProviderSelectionReason",
    "ProviderRuntimeEvent",
    "ProviderRuntimePort",
    "ProviderSnapshot",
    "ProviderStatus",
    "ProviderType",
    "ProviderSelector",
    "QualityScoreBreakdown",
    "QualityScorer",
    "SelectionDecision",
    "UtcClock",
    "UuidIdGenerator",
]
