"""Forward paper-trading domain public API."""

from aic_backend.domain.paper.models import (
    ActivatePaperAccount,
    CapitalMode,
    ExecutionTiming,
    MetricSampleStatus,
    OperationalStatus,
    PaperAccount,
    PaperAccountStatus,
    PaperErrorCode,
    PaperMode,
    PaperOrderIntent,
    PaperPerformanceConfig,
    PaperPerformanceSnapshot,
    PaperPortfolioState,
    PaperProcessingCheckpoint,
    PaperRuntimeError,
    PaperSession,
    PaperSessionResult,
    PaperSessionStatus,
    PaperStateEvent,
    TradeEpisode,
    filled_values,
)
from aic_backend.domain.paper.performance import (
    calculate_performance,
    derive_trade_episodes,
    stable_id,
    trade_statistics,
)

__all__ = [
    "ActivatePaperAccount",
    "CapitalMode",
    "ExecutionTiming",
    "MetricSampleStatus",
    "OperationalStatus",
    "PaperAccount",
    "PaperAccountStatus",
    "PaperErrorCode",
    "PaperMode",
    "PaperOrderIntent",
    "PaperPerformanceConfig",
    "PaperPerformanceSnapshot",
    "PaperPortfolioState",
    "PaperProcessingCheckpoint",
    "PaperRuntimeError",
    "PaperSession",
    "PaperSessionResult",
    "PaperSessionStatus",
    "PaperStateEvent",
    "TradeEpisode",
    "calculate_performance",
    "derive_trade_episodes",
    "filled_values",
    "stable_id",
    "trade_statistics",
]
